'use client';

import { useEffect, useRef, useState } from 'react';
import { ImagePlus, MapPin, Send, Smile } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import type { AppUser, Message } from '@/types/database';
import { StickerPicker } from './StickerPicker';
import { VoiceRecorder } from './VoiceRecorder';

export function Chat({ me, peer }: { me: AppUser; peer: AppUser }) {
  const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(''); const [stickers, setStickers] = useState(false); const [typing, setTyping] = useState(false); const [error, setError] = useState('');
  const bottom = useRef<HTMLDivElement>(null); const typingChannel = useRef<ReturnType<typeof supabase.channel> | null>(null); const typingTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const room = `chat-${[me.id, peer.id].sort().join('-')}`;
  const load = async () => { const { data, error: queryError } = await supabase.from('messages').select('*,sender:users(*)').or(`and(sender_id.eq.${me.id},receiver_id.eq.${peer.id}),and(sender_id.eq.${peer.id},receiver_id.eq.${me.id})`).order('created_at'); if (queryError) setError('Не удалось загрузить сообщения.'); else setMessages((data || []) as Message[]); await supabase.from('messages').update({ read_at: new Date().toISOString() }).eq('receiver_id', me.id).eq('sender_id', peer.id).is('read_at', null); };
  useEffect(() => { void load(); const channel = supabase.channel(room).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, load).on('broadcast', { event: 'typing' }, ({ payload }) => { if (payload.user === peer.id) { setTyping(true); window.setTimeout(() => setTyping(false), 1200); } }).subscribe(); typingChannel.current = channel; return () => { if (typingTimer.current) clearTimeout(typingTimer.current); void supabase.removeChannel(channel); }; }, [me.id, peer.id]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);
  const send = async (type: Message['type'], value?: string, coords?: GeolocationCoordinates) => { if (type === 'text' && !value?.trim()) return; setError(''); const { error: sendError } = await supabase.from('messages').insert({ family_id: me.family_id!, sender_id: me.id, receiver_id: peer.id, type, text: type === 'text' ? value?.trim() : null, sticker_id: type === 'sticker' ? value : null, audio_url: type === 'audio' ? value : null, image_url: type === 'image' ? value : null, latitude: coords?.latitude, longitude: coords?.longitude }); if (sendError) { setError(`Сообщение не отправлено: ${sendError.message}`); return; } setText(''); setStickers(false); };
  const announceTyping = () => { if (!typingChannel.current) return; void typingChannel.current.send({ type: 'broadcast', event: 'typing', payload: { user: me.id } }); if (typingTimer.current) clearTimeout(typingTimer.current); typingTimer.current = setTimeout(() => {}, 900); };
  async function upload(file: Blob, kind: 'audio' | 'image') { const ext = kind === 'audio' ? 'webm' : file.type.split('/')[1] || 'jpg'; const path = `${me.family_id}/${me.id}/${crypto.randomUUID()}.${ext}`; const { error: uploadError } = await supabase.storage.from('family-media').upload(path, file, { contentType: file.type }); if (uploadError) { setError(uploadError.message); return; } const signed = await supabase.storage.from('family-media').createSignedUrl(path, 60 * 60 * 24 * 365); if (signed.error || !signed.data) { setError(signed.error?.message || 'Не удалось открыть файл.'); return; } await send(kind, signed.data.signedUrl); }
  return <div className="flex h-[calc(100dvh-76px-env(safe-area-inset-bottom))] flex-col"><header className="flex items-center gap-3 bg-[var(--tg-card)] p-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-brand font-bold text-white">{peer.display_name[0]}</div><div><b>{peer.display_name}</b><p className="text-xs text-[var(--tg-muted)]">{typing ? 'печатает…' : peer.online ? 'онлайн' : 'не в сети'}</p></div></header><div className="flex-1 overflow-y-auto p-3">{messages.map((message) => <div key={message.id} className={`mb-2 max-w-[82%] rounded-2xl p-3 text-sm ${message.sender_id === me.id ? 'ml-auto bg-brand text-white' : 'bg-[var(--tg-card)]'}`}>{message.type === 'audio' ? <audio controls src={message.audio_url!} /> : message.type === 'image' ? <img className="rounded-lg" src={message.image_url!} alt="Изображение" /> : message.type === 'location' ? <a className="underline" target="_blank" href={`https://www.openstreetmap.org/?mlat=${message.latitude}&mlon=${message.longitude}#map=17/${message.latitude}/${message.longitude}`}>📍 Моя геопозиция</a> : message.type === 'sticker' ? <span className="text-4xl">{message.sticker_id}</span> : message.text}<p className="mt-1 text-right text-[10px] opacity-70">{new Date(message.created_at).toLocaleTimeString('ru', { hour: '2-digit', minute: '2-digit' })}</p></div>)}{!messages.length && <p className="mt-10 text-center text-sm text-[var(--tg-muted)]">Напиши первое сообщение.</p>}<div ref={bottom} /></div>{error && <p className="px-3 pb-2 text-xs text-red-500">{error}</p>}{stickers && <div className="px-3"><StickerPicker onSelect={(sticker) => void send('sticker', sticker)} /></div>}<footer className="flex items-center gap-1 bg-[var(--tg-card)] p-2"><button onClick={() => setStickers(!stickers)} className="p-3 text-brand" aria-label="Стикеры"><Smile /></button><label className="p-3 text-brand" aria-label="Изображение"><ImagePlus /><input className="hidden" type="file" accept="image/*" onChange={(event) => event.target.files?.[0] && void upload(event.target.files[0], 'image')} /></label><VoiceRecorder onReady={(blob) => upload(blob, 'audio')} /><button onClick={() => navigator.geolocation.getCurrentPosition((position) => void send('location', undefined, position.coords), () => setError('Не удалось получить геопозицию.'))} className="p-3 text-brand" aria-label="Геопозиция"><MapPin /></button><input value={text} onChange={(event) => { setText(event.target.value); announceTyping(); }} onKeyDown={(event) => event.key === 'Enter' && void send('text', text)} className="min-w-0 flex-1 rounded-xl bg-slate-100 p-3 text-sm text-ink" placeholder="Сообщение…"/><button onClick={() => void send('text', text)} className="rounded-xl bg-brand p-3 text-white" aria-label="Отправить"><Send size={19} /></button></footer></div>;
}
