'use client';
import dynamic from 'next/dynamic'; import { useCallback,useEffect,useRef,useState } from 'react'; import { supabase } from '@/lib/supabase/client'; import type { AppUser, Location } from '@/types/database'; import { BottomNavigation } from '@/components/BottomNavigation'; import { FamilySetup } from '@/components/FamilySetup'; import { AuthGate } from '@/components/AuthGate'; import { TelegramBootstrap } from '@/components/TelegramBootstrap'; import { MapPin, Users } from 'lucide-react'; import { useRouter } from 'next/navigation';
const FamilyMap=dynamic(()=>import('@/components/FamilyMap').then(x=>x.FamilyMap),{ssr:false,loading:()=> <div className="grid h-full place-items-center">Загрузка карты…</div>});
function MapScreen(){const [me,setMe]=useState<AppUser|null>(null),[locations,setLocations]=useState<Location[]>([]),[sharing,setSharing]=useState(true);const last=useRef(0);const router=useRouter();
const load=useCallback(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data:p}=await supabase.from('users').select('*').eq('id',user.id).single();setMe(p);setSharing(p?.location_sharing_enabled??true);if(p?.family_id){const {data}=await supabase.from('locations').select('*, user:users(*)').order('updated_at',{ascending:false});setLocations((data||[]) as Location[])}},[]);
useEffect(()=>{load();const channel=supabase.channel('family-live').on('postgres_changes',{event:'*',schema:'public',table:'locations'},load).on('postgres_changes',{event:'UPDATE',schema:'public',table:'users'},load).subscribe();return()=>{supabase.removeChannel(channel)}},[load]);
useEffect(()=>{if(!me||!sharing||!navigator.geolocation)return;const watch=navigator.geolocation.watchPosition(async p=>{if(Date.now()-last.current<30000)return;last.current=Date.now();await supabase.from('locations').upsert({user_id:me.id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,updated_at:new Date().toISOString()},{onConflict:'user_id'})},()=>{}, {enableHighAccuracy:true,maximumAge:15000,timeout:15000});return()=>navigator.geolocation.clearWatch(watch)},[me,sharing]);
if(!me)return null;if(!me.family_id)return <FamilySetup onDone={load}/>;const userId=me.id;async function toggle(){const v=!sharing;setSharing(v);await supabase.from('users').update({location_sharing_enabled:v,last_seen:new Date().toISOString(),online:true}).eq('id',userId)}return <main className="app-shell"><header className="absolute z-[500] m-3 flex w-[calc(100%-24px)] items-center justify-between rounded-2xl bg-white/95 p-3 shadow-card"><div><p className="text-xs text-slate-500">Моя семья</p><h1 className="font-bold">Карта близких</h1></div><div className="rounded-xl bg-blue-50 p-2 text-brand"><Users size={20}/></div></header><div className="h-[calc(100dvh-86px)]"><FamilyMap locations={locations} onChat={id=>router.push(`/chats?user=${id}`)}/></div><section className="absolute bottom-24 left-3 right-3 z-[500] rounded-2xl bg-white/95 p-3 shadow-card"><label className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-semibold"><MapPin size={18} className="text-brand"/>Делиться местоположением</span><input checked={sharing} onChange={toggle} type="checkbox" className="h-5 w-5 accent-blue-500"/></label><p className="mt-1 text-xs text-slate-500">Обновление не чаще одного раза в 30 секунд</p></section><BottomNavigation/></main>}
export default function Page(){return <><TelegramBootstrap/><AuthGate><MapScreen/></AuthGate></>}
